baseURL = "/"
defaultContentLanguage  = "en"

title = "Trafiklab"

theme = "trafiklab-2024"
summaryLength = 24

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

refLinksErrorLevel = "WARNING"

[module]
[module.hugoVersion]
extended = true
max = ""
min = "0.122.0"

# paths
[permalinks]
  "/" = "/:title/"
  posts = "/:section/:title/"

# Multilingual
[languages]
  [languages.en]
  languageName = "English"
  weight = 2

  [languages.sv]
  languageName = "Svenska"
  weight = 1
    [languages.sv.permalinks]
      news = "nyheter/:year/:month/:title/"
      cases = "fallstudier/:year/:month/:title/"

# HTML for shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        image = true

[outputFormats]
  [outputFormats.dcat]
    isPlainText = false
    isHTML = false
    permalinkable = true
    mediaType = "application/rdf+xml"
    rel = "alternate"
    protocol = "http://"

[mediaTypes]
  [mediaTypes."application/rdf+xml"]
    suffixes = ["rdf"]

[params]
  devPortalUrl = "https://developer.trafiklab.se"
  sourceRepository = "https://github.com/trafiklab/trafiklab.se/"
  sourceRepositoryBranch = "main"
  support = "https://support.trafiklab.se/"
